apiVersion: apps/v1
kind: Deployment
metadata:
  name: aks1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app1
  template:
    metadata:
      labels:
        app: my-app1
    spec:
      containers:
      - name: my-container1
        image: jyothibasuk/poc-1:v1.$BUILD_ID
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
      imagePullSecrets:
      - name: acrlogin
# service type loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  name: aks1-svc
spec:
  selector:
    app: my-app1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30010
  type: LoadBalancer
# secret
---
apiVersion: v1
kind: Secret
metadata:
    name:acrlogin
type: Opaque
data:
    docker-server: k8srepo.azurecr.io
    docker-username: aksacrtcspoc
    docker-password: hHr6mA5/g7Sdt8uXpuJhmF6ax4IbgKBs